name: start-process

on:
  workflow_call:
    inputs:
      user:
        description: edge device username
        required: true
        type: string
      process-name:
        description: process name
        required: true
        type: string
      slack-channel:
        description: after finish job, send message to this slack channel
        required: true
        type: string
    secrets:
      password:
        description: edge device password
        required: true
      otp:
        description: edge device otp
        required: true

jobs:
  start-process:
    name:   start-process
    runs-on: self-hosted
    steps:
      - name: Checkout the deploy-target repository
        uses: actions/checkout@v2

      - name: Checkout the action repository
        uses: actions/checkout@v2
        with:
          repository: teamdable/vv-deploy-actions
          path: action/

      - name: Get VPN IP of deploy-target devices
        run: |
          action/get-vpn-ip

      - name: start process
        run: |
          echo ${{ secrets.password }} | sudo -S apt-get install expect oathtool -y
          action/start-process.sh --user ${{ inputs.user }} --password ${{ secrets.password }} --otp ${{ secrets.otp }} --process-name ${{ inputs.process-name }} --slack-channel ${{ inputs.slack-channel }}
